num1 = raw_input("Enter a number: ")
num1 = int(num1)
num2 = raw_input("Enter another number: ")
num2 = int(num2)
print "num1 + num2 = " + str(num1+num2)
print "num1 - num2 = " + str(num1-num2)
print "num1 * num2 = " + str(num1*num2)
print "num1 / num2 = " + str(num1/num2)
